### ISSUE TITLE
加粗字体可以修复吗

### ISSUE THREAD

**Issue by CCjun6** [Fogg05/MCsans-Plus#1]
![image](https://github.com/user-attachments/assets/c3f5ea34-e590-424e-ab57-529011374389)
加粗字体很丑 有没有什么办法解决

**Comment by Fogg05** [comment]
没法修复嗷。受限于原版框架，粗体就是这么呈现的，这个被官方代码写死了，材质包没法修改。或许后续mojang会给出相关的功能吧😅
